import ReduxProvider from "@/lib/ReduxProvider";
import ReactQueryProvider from "@/lib/ReactQueryProvider";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { Poppins } from "next/font/google";
import SessionProvider from "@/lib/SessionProvider";

import "./globals.css";

const montserrat = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <SessionProvider>
            <ReduxProvider>
              <ReactQueryProvider>
                <main>{children}</main>
              </ReactQueryProvider>
            </ReduxProvider>
          </SessionProvider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
